### ISSUE TITLE
Problem with cf-for-k8s PR 253 (node can't pull custombuilder-built builder image)

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/capi-k8s-release#46]
We had to revert https://github.com/cloudfoundry/cf-for-k8s/pull/253

The problem is that there was no problem with most of the pipeline, which uses kind. But some of the pipeline tests, and standard manual testing, use GKE, and this code was running into permission problems. In a nutshell, the kpack builder image can be stored in the gcr registry as a  public object, but it can't be retrieved, and we get a failure in the cf-workloads-staging pod. See https://www.pivotaltracker.com/story/show/173470211/comments/215536752 for sample output

**Comment by jamespollard8** [comment]
Eric, one correction I have is that I believe the image is stored in GCR as a private object.

**Comment by jamespollard8** [comment]
After some further investigation, we think the permissions issues we’re seeing affect a specific scenario where:
1) you’re using a GCR (private) registry and
2) your cluster has been configured to use minimal credentials (see this story) and
3) you’re using a GCP service account with minimal permissions (such as "Storage Role")

We suspect this may be a kpack related root cause so we're reach out to them as well ([slack thread](https://cloudfoundry.slack.com/archives/CUWG5TXB5/p1592951320102300))

**Comment by cwlbraa** [comment]
@jamespollard8 can you clarify your comment a bit? The abstract "you"s here are confusing to me - are those conditions that need to be true for kpack to pull successfully or are those the conditions under which it failed?

**Comment by jamespollard8** [comment]
We x-team'd with kpack on this. The solution is to add a docker config secret and add it to the cc-kpack service account as an imagePullSecret. We (relint) are working on the overlay for this now.

**Comment by jamespollard8** [comment]
FWIW We solved the root issue with this overlay: https://github.com/cloudfoundry/cf-for-k8s/blob/d9cf7e018d84bcf07088c94e86a1bf7cada6b253/config/kpack.yml#L39-L55

Also, Connor and I chatted regarding keeping our teams' clusters more in-sync. Consequently, he dropped in this [harden samus GKE security](https://www.pivotaltracker.com/story/show/173537882) chore
